export const INITIAL_SCHEMA_BASELINE_NAME = 'InitialSchemaBaseline2026081300000';

export const INITIAL_SCHEMA_BASELINE_TABLES = [
  'availability_blocks',
  'booking_history',
  'booking_reschedule_requests',
  'booking_table_change_requests',
  'bookings',
  'broadcasts',
  'clients',
  'guest_reviews',
  'hookah_calls',
  'logs',
  'map_objects',
  'restaurant',
  'staff',
  'staff_shift_events',
  'syrve_integrations',
  'tables',
  'zones'
] as const;

export const INITIAL_SCHEMA_BASELINE_ENUMS = [
  'booking_reschedule_requests_status_enum',
  'bookings_source_enum',
  'bookings_status_enum',
  'restaurant_site_mode_enum',
  'restaurant_status_enum',
  'staff_role_enum',
  'staff_shift_events_event_type_enum',
  'tables_status_enum'
] as const;

export const INITIAL_SCHEMA_BASELINE_CRITICAL_INDEXES = [
  'UQ_bookings_active_guest_device_date',
  'UQ_bookings_active_guest_phone_date'
] as const;

export const INITIAL_SCHEMA_BASELINE_CREATE_STATEMENTS = [
  `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`,
  `CREATE TYPE "booking_reschedule_requests_status_enum" AS ENUM ('pending', 'approved', 'rejected', 'cancelled', 'completed')`,
  `CREATE TYPE "bookings_source_enum" AS ENUM ('mini_app', 'phone', 'admin_manual')`,
  `CREATE TYPE "bookings_status_enum" AS ENUM ('pending', 'approved', 'rejected', 'cancelled', 'completed')`,
  `CREATE TYPE "restaurant_site_mode_enum" AS ENUM ('day', 'night', 'holiday')`,
  `CREATE TYPE "restaurant_status_enum" AS ENUM ('open', 'booking_closed', 'closed')`,
  `CREATE TYPE "staff_role_enum" AS ENUM ('owner', 'admin', 'waiter', 'hookah')`,
  `CREATE TYPE "staff_shift_events_event_type_enum" AS ENUM ('shift_started', 'shift_ended', 'shift_auto_ended', 'archived', 'restored')`,
  `CREATE TYPE "tables_status_enum" AS ENUM ('free', 'pending', 'reserved', 'occupied', 'cleaning', 'closed')`,
  `CREATE TABLE "availability_blocks" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "block_date" date NOT NULL,
  "start_time" time without time zone,
  "end_time" time without time zone,
  "reason" text NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "table_id" uuid,
  "zone_id" uuid
)`,
  `CREATE TABLE "booking_history" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "action" character varying(100) NOT NULL,
  "actor_role" character varying(40),
  "actor_staff_id" uuid,
  "actor_name" character varying(160),
  "previous_data" jsonb,
  "new_data" jsonb,
  "reason" text,
  "is_manual_mode" boolean DEFAULT false NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "booking_id" uuid NOT NULL
)`,
  `CREATE TABLE "booking_reschedule_requests" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "requested_date" date NOT NULL,
  "requested_time" time without time zone NOT NULL,
  "status" "booking_reschedule_requests_status_enum" DEFAULT 'pending'::booking_reschedule_requests_status_enum NOT NULL,
  "admin_comment" text,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "resolved_at" timestamp without time zone,
  "booking_id" uuid NOT NULL
)`,
  `CREATE TABLE "booking_table_change_requests" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "requested_table_number" character varying(32),
  "status" character varying(20) DEFAULT 'pending'::character varying NOT NULL,
  "admin_comment" text,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "resolved_at" timestamp without time zone,
  "booking_id" uuid NOT NULL,
  "approved_table_id" uuid
)`,
  `CREATE TABLE "bookings" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "guest_access_token_hash" character varying(64),
  "guest_device_id_hash" character varying(64),
  "guest_phone_normalized" character varying(32),
  "booking_date" date NOT NULL,
  "booking_time" time without time zone NOT NULL,
  "duration_minutes" integer,
  "guests_count" integer NOT NULL,
  "wishes" text,
  "status" "bookings_status_enum" DEFAULT 'pending'::bookings_status_enum NOT NULL,
  "source" "bookings_source_enum" DEFAULT 'mini_app'::bookings_source_enum NOT NULL,
  "approved_at" timestamp without time zone,
  "rejected_at" timestamp without time zone,
  "cancelled_at" timestamp without time zone,
  "cancellation_reason" text,
  "completed_at" timestamp without time zone,
  "checked_in_at" timestamp without time zone,
  "late_notified_at" timestamp without time zone,
  "lateness_hours" integer,
  "lateness_minutes" integer,
  "expected_arrival_at" timestamp without time zone,
  "guest_notification" jsonb,
  "manual_change_reason" text,
  "manually_changed_at" timestamp without time zone,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  "table_id" uuid,
  "client_id" uuid,
  "created_by_staff_id" uuid
)`,
  `CREATE TABLE "broadcasts" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "title" character varying,
  "message" text NOT NULL,
  "target" character varying DEFAULT 'all_clients'::character varying NOT NULL,
  "sent_at" timestamp without time zone,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "created_by_staff_id" uuid
)`,
  `CREATE TABLE "clients" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "full_name" character varying NOT NULL,
  "phone" character varying NOT NULL,
  "telegram_id" bigint,
  "visits_count" integer DEFAULT 0 NOT NULL,
  "total_guests" integer DEFAULT 0 NOT NULL,
  "cancellations_count" integer DEFAULT 0 NOT NULL,
  "reschedules_count" integer DEFAULT 0 NOT NULL,
  "last_visit_at" timestamp without time zone,
  "note" text,
  "is_regular" boolean DEFAULT false NOT NULL,
  "is_blacklisted" boolean DEFAULT false NOT NULL,
  "blacklist_reason" text,
  "blacklisted_at" timestamp without time zone,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
)`,
  `CREATE TABLE "guest_reviews" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "text" text NOT NULL,
  "is_published" boolean DEFAULT false NOT NULL,
  "published_at" timestamp without time zone,
  "external_review_opened_at" timestamp without time zone,
  "response_text" text,
  "responded_at" timestamp without time zone,
  "responded_by_name" character varying(160),
  "responded_by_role" character varying(32),
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  "booking_id" uuid NOT NULL
)`,
  `CREATE TABLE "hookah_calls" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "status" character varying(20) DEFAULT 'new'::character varying NOT NULL,
  "eta_minutes" integer,
  "eta_due_at" timestamp without time zone,
  "waiter_name" character varying(160),
  "accepted_at" timestamp without time zone,
  "completed_at" timestamp without time zone,
  "cancelled_at" timestamp without time zone,
  "cancel_reason" text,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  "booking_id" uuid NOT NULL,
  "table_id" uuid,
  "accepted_by_staff_id" uuid
)`,
  `CREATE TABLE "logs" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "action" character varying NOT NULL,
  "details" jsonb,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "staff_id" uuid
)`,
  `CREATE TABLE "map_objects" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "object_type" character varying NOT NULL,
  "name" character varying,
  "x" numeric DEFAULT '0'::numeric NOT NULL,
  "y" numeric DEFAULT '0'::numeric NOT NULL,
  "width" numeric DEFAULT '100'::numeric NOT NULL,
  "height" numeric DEFAULT '100'::numeric NOT NULL,
  "rotation" numeric DEFAULT '0'::numeric NOT NULL,
  "color" character varying,
  "is_visible" boolean DEFAULT true NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  "restaurant_id" uuid,
  "zone_id" uuid
)`,
  `CREATE TABLE "restaurant" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "name" character varying DEFAULT 'MOLO Restaurant'::character varying NOT NULL,
  "phone" character varying,
  "admin_can_manage_zones" boolean DEFAULT false NOT NULL,
  "admin_can_manage_online_booking" boolean DEFAULT false NOT NULL,
  "admin_can_manage_restaurant" boolean DEFAULT false NOT NULL,
  "admin_can_change_site_mode" boolean DEFAULT false NOT NULL,
  "admin_can_edit_restaurant_settings" boolean DEFAULT false NOT NULL,
  "admin_can_manage_blacklist" boolean DEFAULT false NOT NULL,
  "admin_can_respond_reviews" boolean DEFAULT false NOT NULL,
  "admin_can_manage_staff_shifts" boolean DEFAULT false NOT NULL,
  "admin_can_send_broadcasts" boolean DEFAULT false NOT NULL,
  "hookah_calls_available" boolean DEFAULT true NOT NULL,
  "hookah_calls_availability_changed_at" timestamp without time zone,
  "address" text,
  "menu_url" text,
  "logo_url" text,
  "main_photo_url" text,
  "open_time" time without time zone DEFAULT '10:00:00'::time without time zone NOT NULL,
  "booking_close_time" time without time zone DEFAULT '22:00:00'::time without time zone NOT NULL,
  "close_time" time without time zone DEFAULT '23:00:00'::time without time zone NOT NULL,
  "status" "restaurant_status_enum" DEFAULT 'open'::restaurant_status_enum NOT NULL,
  "site_mode" "restaurant_site_mode_enum" DEFAULT 'night'::restaurant_site_mode_enum NOT NULL,
  "holiday_key" character varying(32),
  "close_message" text DEFAULT 'Ресторан зараз зачинений. Ми працюємо з 10:00 до 23:00.'::text NOT NULL,
  "booking_closed_message" text DEFAULT 'Онлайн-бронювання завершено. Для бронювання зателефонуйте адміністратору.'::text NOT NULL,
  "map_width" numeric DEFAULT '1600'::numeric NOT NULL,
  "map_height" numeric DEFAULT '1000'::numeric NOT NULL,
  "booking_close_notified_at" date,
  "restaurant_close_notified_at" date,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
)`,
  `CREATE TABLE "staff" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "telegram_id" bigint,
  "telegram_invite_token_hash" text,
  "telegram_invite_expires_at" timestamp without time zone,
  "full_name" character varying NOT NULL,
  "phone" character varying,
  "role" "staff_role_enum" DEFAULT 'waiter'::staff_role_enum NOT NULL,
  "pin_hash" text,
  "director_login_name" character varying(64),
  "director_password_hash" text,
  "director_credentials_configured_at" timestamp without time zone,
  "director_failed_login_attempts" integer DEFAULT 0 NOT NULL,
  "director_locked_until" timestamp without time zone,
  "note" text,
  "active" boolean DEFAULT true NOT NULL,
  "is_archived" boolean DEFAULT false NOT NULL,
  "is_on_shift" boolean DEFAULT false NOT NULL,
  "shift_started_at" timestamp without time zone,
  "shift_started_by" character varying,
  "shift_ended_at" timestamp without time zone,
  "shift_ended_by" character varying,
  "last_auto_shift_end_date" date,
  "archived_at" timestamp without time zone,
  "archived_by" character varying,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
)`,
  `CREATE TABLE "staff_shift_events" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "event_type" "staff_shift_events_event_type_enum" NOT NULL,
  "performed_by" character varying,
  "comment" text,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "staffId" uuid NOT NULL
)`,
  `CREATE TABLE "syrve_integrations" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "display_name" character varying(120) DEFAULT 'MOLO · Syrve'::character varying NOT NULL,
  "api_base_url" text DEFAULT 'https://api-eu.syrve.live'::text NOT NULL,
  "api_login_encrypted" text,
  "api_login_iv" character varying(64),
  "api_login_auth_tag" character varying(64),
  "api_login_masked" character varying(160),
  "organization_id" character varying(160),
  "organization_name" character varying(240),
  "status" character varying(32) DEFAULT 'not_connected'::character varying NOT NULL,
  "last_checked_at" timestamp without time zone,
  "connected_at" timestamp without time zone,
  "last_error" text,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL
)`,
  `CREATE TABLE "tables" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "table_number" character varying NOT NULL,
  "seats" integer DEFAULT 4 NOT NULL,
  "shape" character varying DEFAULT 'rectangle'::character varying NOT NULL,
  "photo_url" text,
  "status" "tables_status_enum" DEFAULT 'free'::tables_status_enum NOT NULL,
  "x" numeric DEFAULT '0'::numeric NOT NULL,
  "y" numeric DEFAULT '0'::numeric NOT NULL,
  "width" numeric DEFAULT '100'::numeric NOT NULL,
  "height" numeric DEFAULT '80'::numeric NOT NULL,
  "rotation" numeric DEFAULT '0'::numeric NOT NULL,
  "is_visible" boolean DEFAULT true NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  "zone_id" uuid
)`,
  `CREATE TABLE "zones" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "name" character varying NOT NULL,
  "color" character varying,
  "photo_url" text,
  "description" text,
  "x" numeric DEFAULT '0'::numeric NOT NULL,
  "y" numeric DEFAULT '0'::numeric NOT NULL,
  "width" numeric DEFAULT '300'::numeric NOT NULL,
  "height" numeric DEFAULT '200'::numeric NOT NULL,
  "rotation" numeric DEFAULT '0'::numeric NOT NULL,
  "is_closed" boolean DEFAULT false NOT NULL,
  "is_visible" boolean DEFAULT true NOT NULL,
  "created_at" timestamp without time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp without time zone DEFAULT now() NOT NULL,
  "restaurant_id" uuid
)`
] as const;
