import { INITIAL_SCHEMA_BASELINE_NAME } from './initial-schema-baseline-definition';

export const INITIAL_SCHEMA_BASELINE_ADOPTION_RUNTIME_MIGRATIONS = [
  'CreateStaffPinAttempts2026081400010',
  'UpgradeStaffPinAttemptsPerAttempt2026081400020',
  'CreateWaiterCalls2026081500010',
  'AddWaiterCallAssignmentActive2026081500015',
  'CloseInactiveWaiterCalls2026081500020',
] as const;

export const INITIAL_SCHEMA_BASELINE_ADOPTED_HISTORY = [
  ...INITIAL_SCHEMA_BASELINE_ADOPTION_RUNTIME_MIGRATIONS,
  INITIAL_SCHEMA_BASELINE_NAME,
] as const;

export const INITIAL_SCHEMA_BASELINE_FRESH_REVERT_HISTORY = [
  INITIAL_SCHEMA_BASELINE_NAME,
] as const;
